In [ ]:
import pandas as pd

In [ ]:
# Define column names
cols = [
    'SepalLengthCm',
    'SepalWidthCm',
    'PetalLengthCm',
    'PetalWidthCm',
    'Species'
]

# Load dataset with custom column names
df = pd.read_csv("Iris.csv", names=cols)
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
# g. Create subsets
setosa = df[df['Species'] == 'Iris-setosa']
versicolor = df[df['Species'] == 'Iris-versicolor']
virginica = df[df['Species'] == 'Iris-virginica']

In [ ]:
# h. Merge subsets
merged_data = pd.concat([setosa, versicolor, virginica])
merged_data

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
# i. Sort by Petal Length
sorted_data = df.sort_values(by='PetalLengthCm')
sorted_data

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
22             4.6           3.6            1.0           0.2     Iris-setosa
13             4.3           3.0            1.1           0.1     Iris-setosa
14             5.8           4.0            1.2           0.2     Iris-setosa
35             5.0           3.2            1.2           0.2     Iris-setosa
16             5.4           3.9            1.3           0.4     Iris-setosa
..             ...           ...            ...           ...             ...
131            7.9           3.8            6.4           2.0  Iris-virginica
105            7.6           3.0            6.6           2.1  Iris-virginica
117            7.7           3.8            6.7           2.2  Iris-virginica
122            7.7           2.8            6.7           2.0  Iris-virginica
118            7.7           2.6            6.9           2.3  Iris-virginica

[150 rows x 5 columns]

In [ ]:
# j. Transpose data
transposed_data = df.transpose()
transposed_data

,0,1,2,3,4,5,6,7,8,9,...,140,141,142,143,144,145,146,147,148,149
SepalLengthCm,5.1,4.9,4.7,4.6,5.0,5.4,4.6,5.0,4.4,4.9,...,6.7,6.9,5.8,6.8,6.7,6.7,6.3,6.5,6.2,5.9
SepalWidthCm,3.5,3.0,3.2,3.1,3.6,3.9,3.4,3.4,2.9,3.1,...,3.1,3.1,2.7,3.2,3.3,3.0,2.5,3.0,3.4,3.0
PetalLengthCm,1.4,1.4,1.3,1.5,1.4,1.7,1.4,1.5,1.4,1.5,...,5.6,5.1,5.1,5.9,5.7,5.2,5.0,5.2,5.4,5.1
PetalWidthCm,0.2,0.2,0.2,0.2,0.2,0.4,0.3,0.2,0.2,0.1,...,2.4,2.3,1.9,2.3,2.5,2.3,1.9,2.0,2.3,1.8
Species,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,...,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica

In [ ]:
# k. Melt data
melted_data = pd.melt(df,
                      id_vars=["Species"],
                      value_vars=['PetalLengthCm', 'SepalLengthCm']
)
melted_data

            Species       variable  value
0       Iris-setosa  PetalLengthCm    1.4
1       Iris-setosa  PetalLengthCm    1.4
2       Iris-setosa  PetalLengthCm    1.3
3       Iris-setosa  PetalLengthCm    1.5
4       Iris-setosa  PetalLengthCm    1.4
..              ...            ...    ...
295  Iris-virginica  SepalLengthCm    6.7
296  Iris-virginica  SepalLengthCm    6.3
297  Iris-virginica  SepalLengthCm    6.5
298  Iris-virginica  SepalLengthCm    6.2
299  Iris-virginica  SepalLengthCm    5.9

[300 rows x 3 columns]

In [ ]:
# l. Cast to wide format
wide_formated_data = melted_data.pivot_table(
    index = 'Species',
    columns = 'variable',
    values='value',
    aggfunc='mean'
)
wide_formated_data

variable         PetalLengthCm  SepalLengthCm
Species
Iris-setosa              1.464          5.006
Iris-versicolor          4.260          5.936
Iris-virginica           5.552          6.588